export const shoes = [
	{
		id: 1,
		brand: "Adidas",
		color: "As shown",
		title: "MND S1 RAYT Black",
		desc: "Offering functional design in which every element and detail serve a purpose",
		price: 28.99,
		img: ["/p1.jpg", "/p2.jpg", "/p3.jpg"],
	},
	{
		id: 2,
		brand: "Adidas",
		color: "As shown",
		title: "Hu NWD Animal Print Amber",
		desc: "Offering functional design in which every element and detail serve a purpose",
		price: 28.99,
		img: ["/p4.jpg", "/p5.jpg", "/p6.jpg"],
	},
	{
		id: 3,
		brand: "Adidas",
		color: "As shown",
		title: "Hu NWD Animal Print Grey",
		desc: "Offering functional design in which every element and detail serve a purpose",
		price: 28.99,
		img: ["/p7.jpg", "/p8.jpg", "/p9.jpg", "/p10.jpg", "/p11.jpg"],
	},
	{
		id: 4,
		brand: "Adidas",
		color: "As shown",
		title: "MND S1 RAYT Blue",
		desc: "Offering functional design in which every element and detail serve a purpose",
		price: 28.99,
		img: ["/p12.jpg", "/p13.jpg", "/p14.jpg"],
	},
	{
		id: 5,
		brand: "Adidas",
		color: "As shown",
		title: "Bad Bunny First Cafe",
		desc: "Offering functional design in which every element and detail serve a purpose",
		price: 28.99,
		img: ["/p15.jpg", "/p16.jpg", "/p17.jpg",'/p18.png'],
	},
];
